name: Deploy to Render

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Trigger Render deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trigger Render deploy via API
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          if [ -z "$RENDER_API_KEY" ] || [ -z "$RENDER_SERVICE_ID" ]; then
            echo "RENDER_API_KEY or RENDER_SERVICE_ID is not set. Add them in the repo Settings > Secrets." >&2
            exit 1
          fi
          echo "Triggering deploy for service $RENDER_SERVICE_ID"
          curl -s -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys \
            -d '{}' | jq .
